# Generated by Django 3.1.5 on 2021-01-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectAwwards', '0002_auto_20210125_0123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='date_craeted',
            new_name='date_created',
        ),
    ]
