# Generated by Django 3.1.5 on 2021-01-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectAwwards', '0003_auto_20210125_2218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMerch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=40)),
                ('description', models.TextField()),
                ('url_link', models.DecimalField(decimal_places=2, max_digits=20)),
                ('bio', models.TextField()),
                ('profile_pic', models.ImageField(blank='true', default='default.png', upload_to='profile/')),
            ],
        ),
    ]
